package generatedbyassl.as.aes.consumer.aeip.messages;

import java.io.Serializable;
import generatedbyassl.as.ASSLMESSAGE;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'getRequest' (specified as MESSAGE ASSL tier).
 */
public class GETREQUEST
	extends ASSLMESSAGE
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'GETREQUEST' class.
	 */
	static private GETREQUEST oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  GETREQUEST (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'GETREQUEST' class.
	 */
	static public GETREQUEST getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new GETREQUEST();
		}
		return oInstance;
	}

}