package generatedbyassl.as.aes.buffer.aeip.channels;

import java.io.Serializable;
import generatedbyassl.as.ASSLCHANNEL;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'BufferInputChannel' (specified as CHANNEL ASSL tier).
 */
public class BUFFERINPUTCHANNEL
	extends ASSLCHANNEL
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'BUFFERINPUTCHANNEL' class.
	 */
	static private BUFFERINPUTCHANNEL oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  BUFFERINPUTCHANNEL (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'BUFFERINPUTCHANNEL' class.
	 */
	static public BUFFERINPUTCHANNEL getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new BUFFERINPUTCHANNEL();
		}
		return oInstance;
	}

}