package generatedbyassl.as.aes.producer.aeip.functions;

import java.io.Serializable;
import generatedbyassl.as.ASSLFUNCTION;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'sendPutRequest' (specified as FUNCTION ASSL tier).
 */
public class SENDPUTREQUEST
	extends ASSLFUNCTION
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'SENDPUTREQUEST' class.
	 */
	static private SENDPUTREQUEST oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  SENDPUTREQUEST (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'SENDPUTREQUEST' class.
	 */
	static public SENDPUTREQUEST getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new SENDPUTREQUEST();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Embeds statements to be performed by the function.
	 */
	public void DOES (  )
	{
		super.DOES();
		generatedbyassl.as.aes.producer.aeip.channels.PRODUCERTOBUFFER.getInstance().putMessage("generatedbyassl.as.aes.producer.aeip.messages.PUTREQUEST", generatedbyassl.as.aes.producer.aeip.messages.PUTREQUEST.getInstance());
	}

}