package generatedbyassl.as.aes.producer.aeself_management.self_healing;

import java.io.Serializable;
import generatedbyassl.as.*;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'inSending' (specified as FLUENT ASSL tier).
 */
public class INSENDING
	extends ASSLFLUENT
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'INSENDING' class.
	 */
	static private INSENDING oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  INSENDING (  )
	{
		vInitiatedByEvents.add( generatedbyassl.as.aes.producer.events.TIMETOSEND.getInstance() );
		generatedbyassl.as.aes.producer.events.TIMETOSEND.getInstance().addEventCatcher(this); //**** fluent registers for that event
		vTerminatedByEvents.add( generatedbyassl.as.aes.producer.events.CONFIRMATION.getInstance() );
		generatedbyassl.as.aes.producer.events.CONFIRMATION.getInstance().addEventCatcher(this); //**** fluent registers for that event
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'INSENDING' class.
	 */
	static public INSENDING getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new INSENDING();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method calls all the fluent-mapped actions in sequence.
	 */
	protected synchronized void callFluentActions (  )
	{
	}

}