package generatedbyassl.as.aes.producer.aeip.managed_elements;

import java.io.Serializable;
import generatedbyassl.as.ASSLMANAGED_ELEMENT;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'Consumer' (specified as MANAGED_ELEMENT ASSL tier).
 */
public class CONSUMER
	extends ASSLMANAGED_ELEMENT
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'CONSUMER' class.
	 */
	static private CONSUMER oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  CONSUMER (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'CONSUMER' class.
	 */
	static public CONSUMER getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new CONSUMER();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Management element interface function.
	 */
	public void PUTINBUFFER (  )
	{
		//**** Implement this method.
	}

}