package generatedbyassl.as.aes;

import java.io.Serializable;
import generatedbyassl.as.ASSLAE;
import generatedbyassl.as.aes.buffer.controlloop.*;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'Buffer' (specified as AE ASSL tier).
 */
public class BUFFER
	extends ASSLAE
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'BUFFER' class.
	 */
	static private BUFFER oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds a reference to the AE control loop's monitor.
	 */
	private BUFFER_ASSLMONITOR oMonitor = new BUFFER_ASSLMONITOR();
	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds a reference to the AE control loop's analyzer.
	 */
	private BUFFER_ASSLANALYZER oAnalyzer = new BUFFER_ASSLANALYZER();
	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds a reference to the AE control loop's simulator.
	 */
	private BUFFER_ASSLSIMULATOR oSimulator = new BUFFER_ASSLSIMULATOR();
	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds a reference to the AE control loop's executor.
	 */
	private BUFFER_ASSLEXECUTOR oExecutor = new BUFFER_ASSLEXECUTOR();
	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds a reference to the FRIENDS class.
	 */
	public generatedbyassl.as.aes.buffer.FRIENDS FRIENDS = generatedbyassl.as.aes.buffer.FRIENDS.getInstance();
	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds a reference to the AEIP class.
	 */
	public generatedbyassl.as.aes.buffer.AEIP AEIP = generatedbyassl.as.aes.buffer.AEIP.getInstance();

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  BUFFER (  )
	{
		vPolicies.put( "SELF_HEALING", generatedbyassl.as.aes.buffer.aeself_management.SELF_HEALING.getInstance() );
		ACTIONS.put( "BUFFEREXPANSION", generatedbyassl.as.aes.buffer.actions.BUFFEREXPANSION.getInstance() );
		ACTIONS.put( "BUFFERREDUCTION", generatedbyassl.as.aes.buffer.actions.BUFFERREDUCTION.getInstance() );
		ACTIONS.put( "PUTELEMENT", generatedbyassl.as.aes.buffer.actions.PUTELEMENT.getInstance() );
		ACTIONS.put( "GETELEMENT", generatedbyassl.as.aes.buffer.actions.GETELEMENT.getInstance() );
		EVENTS.put( "ISGETELEMENTREQUESTED", generatedbyassl.as.aes.buffer.events.ISGETELEMENTREQUESTED.getInstance() );
		EVENTS.put( "ISPUTELEMENTREQUESTED", generatedbyassl.as.aes.buffer.events.ISPUTELEMENTREQUESTED.getInstance() );
		EVENTS.put( "BUFFERFULL", generatedbyassl.as.aes.buffer.events.BUFFERFULL.getInstance() );
		EVENTS.put( "BUFFEREMPTY", generatedbyassl.as.aes.buffer.events.BUFFEREMPTY.getInstance() );
		EVENTS.put( "BUFFERNOTEMPTY", generatedbyassl.as.aes.buffer.events.BUFFERNOTEMPTY.getInstance() );
		EVENTS.put( "BUFFERNOTFULL", generatedbyassl.as.aes.buffer.events.BUFFERNOTFULL.getInstance() );
		METRICS.put( "BUFFERFULL", generatedbyassl.as.aes.buffer.metrics.BUFFERFULL.getInstance() );
		METRICS.put( "BUFFEREMPTY", generatedbyassl.as.aes.buffer.metrics.BUFFEREMPTY.getInstance() );
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'BUFFER' class.
	 */
	static public BUFFER getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new BUFFER();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Sets the control loop components.
	 */
	protected void setControlLoop (  )
	{
		//**** This method overrides the super class's method.
		//****************************************************
		oMonitor.setMonitoredSLO(AESLO);
		oMonitor.setMonitoredMetrics(METRICS);
		oMonitor.setAnalyzer(oAnalyzer);
		oAnalyzer.setSimulator(oSimulator);
		oAnalyzer.setExecutor(oExecutor);
		oSimulator.setExecutor(oExecutor);
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Performs the AE control loop.
	 */
	protected void controlLoop (  )
	{
		//**** This method overrides the super class's method.
		//****************************************************
		try
		{
			//**** control loops should not be very resource-consuming, thus it releases CPU for a while
			Thread.sleep(1000);
		}
		catch ( InterruptedException ex ) 
		{
			System.err.println( ex.getMessage() );
		}
		//**** performs AE control loop monitor-analyzer-simulator-executor
		oMonitor.perform();
		oAnalyzer.perform();
		oSimulator.perform();
		oExecutor.perform();
		//**** applies all the "switched-on" self-management policies for the AS
		applayPolicies();
	}

}