package generatedbyassl.as.aes.consumer.controlloop;

import generatedbyassl.as.controlloop.ASSLEXECUTOR;

/**
 * Generated by ASSL Framework
 * 
 * This is the executor class of the consumer's control loop. An instance of this class participates in the monitor-analyzer-simulator-executor control loop of consumer.
 */
public class CONSUMER_ASSLEXECUTOR
	extends ASSLEXECUTOR
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * The superclass ASSLEXECUTOR makes this class fully functional. Put your modifications here (if any).
	 */

}