package generatedbyassl.as.aes.buffer.actions;

import java.io.Serializable;
import generatedbyassl.as.ASSLACTION;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'bufferExpansion' (specified as ACTION ASSL tier).
 */
public class BUFFEREXPANSION
	extends ASSLACTION
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'BUFFEREXPANSION' class.
	 */
	static private BUFFEREXPANSION oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  BUFFEREXPANSION (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'BUFFEREXPANSION' class.
	 */
	static public BUFFEREXPANSION getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new BUFFEREXPANSION();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Provides conditions to be fulfilled before processing the action.
	 */
	public boolean GUARDS (  )
	{
		boolean bResult = true;
		bResult =  generatedbyassl.as.aes.buffer.aeself_management.self_healing.INBUFFERFULL.getInstance().isFluentInitiated()  ;
		return bResult;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Embeds statements to be performed by the action if the GURADS conditions are fulfilled.
	 */
	public void DOES ( int iCurrentCapacity,int BUFFER_SIZE )
	{
		super.DOES();
		generatedbyassl.as.aes.buffer.aeip.managed_elements.BUFFER.getInstance().EXPAND(iCurrentCapacity,BUFFER_SIZE);
	}

}
