package generatedbyassl.as.aes.buffer.actions;

import java.io.Serializable;
import java.util.Date;

import generatedbyassl.as.ASSLACTION;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'getElement' (specified as ACTION ASSL tier).
 */
public class GETELEMENT
	extends ASSLACTION
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'GETELEMENT' class.
	 */
	static private GETELEMENT oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  GETELEMENT (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'GETELEMENT' class.
	 */
	static public GETELEMENT getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new GETELEMENT();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Provides conditions to be fulfilled before processing the action.
	 */
	public boolean GUARDS (  )
	{
		boolean bResult = true;
		bResult =  generatedbyassl.as.aes.buffer.aeself_management.self_healing.INGETELEMENTREQUESTED.getInstance().isFluentInitiated()  &&  !  generatedbyassl.as.aes.buffer.metrics.BUFFEREMPTY.getInstance().isValid()  ;
		return bResult;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Embeds statements to be performed by the action if the GURADS conditions are fulfilled.
	 */
	public void DOES ( Date poBufferElement  )
	{
		super.DOES();
		/*****1*****/

		generatedbyassl.as.aes.buffer.aeip.managed_elements.BUFFER.getInstance().GETFROMBUFFER(poBufferElement);
	}

}
