package generatedbyassl.as.aes.buffer.metrics;

import java.io.Serializable;
import generatedbyassl.as.ASSLMETRIC;
import java.lang.Integer;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'bufferFull' (specified as METRIC ASSL tier).
 */
public class BUFFERFULL
	extends ASSLMETRIC
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'BUFFERFULL' class.
	 */
	static private BUFFERFULL oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;
	/**
	 * Generated by ASSL Framework
	 * 
	 * The metric's value - ASSL VALUE {} clause.
	 */
	public Integer VALUE = new Integer(new Float(0).intValue());
	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds the old VALUE of the metric.
	 */
	protected Integer oldVALUE = new Integer(new Float(0).intValue());

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  BUFFERFULL (  )
	{
		METRIC_TYPE = "RESOURCE";
		DESCRIPTION = "determines if the buffer can be written";
		MEASURE_UNIT = "INTEGER";
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'BUFFERFULL' class.
	 */
	static public BUFFERFULL getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new BUFFERFULL();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Checks whether the metric is valid. A metric is considered valid (true) iff the value it is holding satisfies all the threshold class values.
	 */
	public synchronized boolean isValid (  )
	{
		boolean bValid = false;
		Integer sValues[] = {  new Integer( new Float(100).intValue() ) };
		for ( int i = 0; i < sValues.length; i++ ) 
		{
			int iEqual = VALUE.compareTo( sValues[i] );
			if ( iEqual == 0 ) 
			{
				bValid = true;
				break;
			}
		}
		return bValid;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Updates the metric value.
	 */
	public synchronized void refresh (  )
	{
		//**** checks if the metric has changed its VALUE since the last refresh
		int iEql = VALUE.compareTo( oldVALUE );
		if ( iEql == 0 ) 
		{
			bHasChanged = false;
		}
		else
		{
			oldVALUE = new Integer( VALUE.intValue() );
			bHasChanged = true;
		}
	}

}