package generatedbyassl.as.aes.consumer.aeself_management.self_healing;

import java.io.Serializable;
import generatedbyassl.as.*;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'inReceiving' (specified as FLUENT ASSL tier).
 */
public class INRECEIVING
	extends ASSLFLUENT
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'INRECEIVING' class.
	 */
	static private INRECEIVING oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  INRECEIVING (  )
	{
		vInitiatedByEvents.add( generatedbyassl.as.aes.consumer.events.TIMETORECEIVE.getInstance() );
		generatedbyassl.as.aes.consumer.events.TIMETORECEIVE.getInstance().addEventCatcher(this); //**** fluent registers for that event
		vTerminatedByEvents.add( generatedbyassl.as.aes.consumer.events.CONFIRMATION.getInstance() );
		generatedbyassl.as.aes.consumer.events.CONFIRMATION.getInstance().addEventCatcher(this); //**** fluent registers for that event
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'INRECEIVING' class.
	 */
	static public INRECEIVING getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new INRECEIVING();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method calls all the fluent-mapped actions in sequence.
	 */
	protected synchronized void callFluentActions (  )
	{
	}

}