package generatedbyassl.as.boundedbuffer.asself_management.self_healing;

import java.io.Serializable;
import generatedbyassl.as.*;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'inBufferFull' (specified as FLUENT ASSL tier).
 */
public class INBUFFERFULL
	extends ASSLFLUENT
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'INBUFFERFULL' class.
	 */
	static private INBUFFERFULL oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  INBUFFERFULL (  )
	{
		vInitiatedByEvents.add( generatedbyassl.as.boundedbuffer.events.BUFFERFULL.getInstance() );
		generatedbyassl.as.boundedbuffer.events.BUFFERFULL.getInstance().addEventCatcher(this); //**** fluent registers for that event
		vTerminatedByEvents.add( generatedbyassl.as.boundedbuffer.events.NOTIFIED.getInstance() );
		generatedbyassl.as.boundedbuffer.events.NOTIFIED.getInstance().addEventCatcher(this); //**** fluent registers for that event
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'INBUFFERFULL' class.
	 */
	static public INBUFFERFULL getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new INBUFFERFULL();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method calls all the fluent-mapped actions in sequence.
	 */
	protected synchronized void callFluentActions (  )
	{
	}

}